[tool.briefcase]
project_name = "Hello World"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/helloworld"
license = "BSD license"
author = 'Agilulfe'
author_email = "l.nicaud@eleves-alsacienne.org"

[tool.briefcase.app.helloworld]
formal_name = "Hello World"
description = "My first application"
icon = "src/helloworld/resources/helloworld"
sources = ['src/helloworld']
requires = [
]


[tool.briefcase.app.helloworld.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.helloworld.linux]
requires = [
    'toga-gtk>=0.3.0.dev34',
]

[tool.briefcase.app.helloworld.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.helloworld.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.helloworld.windows]
requires = [
    'toga-winforms>=0.3.0.dev34',
]

# Mobile deployments
[tool.briefcase.app.helloworld.iOS]
requires = [
    'toga-iOS>=0.3.0.dev34',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.helloworld.android]
requires = [
    'toga-android>=0.3.0.dev34'
]
